# Generated by Django 5.1.2 on 2024-11-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_email_alter_user_passage_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Professor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=16)),
                ("email", models.EmailField(max_length=255)),
                ("nome", models.CharField(max_length=45)),
            ],
            options={
                "verbose_name_plural": "Professores",
            },
        ),
    ]
