# Generated by Django 5.1.2 on 2024-11-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_turma"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nomeAluno", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("turma", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.turma")),
            ],
        ),
    ]
