# Generated by Django 5.1.2 on 2024-11-29 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_aluno"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ocorrencia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao", models.CharField(max_length=255)),
                ("data_criacao", models.DateField()),
                ("aluno", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.aluno")),
                (
                    "usuario",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
