# Generated by Django 5.1.2 on 2024-11-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_ocorrencia"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aluno",
            old_name="nomeAluno",
            new_name="nome",
        ),
    ]
