# Generated by Django 5.1.2 on 2024-11-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rename_nomealuno_aluno_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrencia",
            name="categoria_ocorrencia",
            field=models.IntegerField(
                choices=[(1, "Atraso"), (2, "Sem uniforme"), (3, "Reunião no NUPE"), (4, "Outro")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="ocorrencia",
            name="descricao",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
