# Generated by Django 5.1.2 on 2024-11-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_trimestre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trimestre",
            name="nome",
        ),
        migrations.AddField(
            model_name="trimestre",
            name="periodo",
            field=models.IntegerField(choices=[(1, "Primeiro"), (2, "Segundo"), (3, "Terceiro")], default=1),
        ),
    ]
