# Generated by Django 5.1.2 on 2024-11-29 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_conselhoclasse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="PreConselho",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao_trimestre", models.CharField(max_length=1000)),
                (
                    "trimestre",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.trimestre",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.turma",
                    ),
                ),
            ],
        ),
    ]
