# Generated by Django 5.1.3 on 2024-11-30 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_aluno_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nota",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nota", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "aluno",
                    models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to="core.aluno"),
                ),
                (
                    "conselhoClasse",
                    models.ForeignKey(
                        default=None, on_delete=django.db.models.deletion.PROTECT, to="core.conselhoclasse"
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to="core.disciplina"),
                ),
                (
                    "trimestre",
                    models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to="core.trimestre"),
                ),
            ],
        ),
    ]
